version: '3.6'

services:
  proxy:
    image: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../config/traefik.toml:/etc/traefik/traefik.toml:ro
      - ../config/acme.json:/acme.json
    networks:
      default:
        aliases:
          - api.cryptotradingkit.com
          - auth.cryptotradingkit.com
          - ws.ranger.cryptotradingkit.com
          - pma.cryptotradingkit.com
          - eth.cryptotradingkit.com
          - monitor.cryptotradingkit.com
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: monitor.cryptotradingkit.com'
      traefik.port: 8080
